### ISSUE TITLE
In areaahull(alpha_hull) : Problem in area computation (Returns NA)

### ISSUE THREAD

**Issue by csbbcompbio** [jw156605/SLICER#5]
Dear Authors,
I have been trying to run SLICER and facing the error on sample dataset ["In areaahull(alpha_hull) : Problem in area computation (Returns NA)"]. I have tied installing and running SLICER on R/3.3.3 and also R/3.4.1. I face the same error on both the versions of R.
Can you please help me with this error.

Cheers !!
Praneet

**Comment by jw156605** [comment]
Hi Praneet, this is not an error, just a warning. It happens because the alphahull package returns NA whenever it is given a set of points that have some duplicate coordinates. This can occur for small values of k, when LLE embeds some points at the same coordinates. The select_k function handles this case automatically. If you're concerned about the warning, you can do
`k = suppressWarnings(select_k(traj[,genes],kmin=5))`

**Comment by csbbcompbio** [comment]
Awesome. I was able to run all the other steps but warning was saying return as NA that's why I was concerned. Other question is I am running it on 10x data with 9500 cells and 27500 genes. Is this data very huge to be handled or Slicer can take care of huge datasets.

Thanks,
Cheers !!
Praneet

**Comment by jw156605** [comment]
I haven't tried it on a dataset that large yet. But, based on my experience with smaller datasets, I would highly recommend pre-filtering cells to make sure that you include only cells that you expect to form a single trajectory. For example, if you're looking at brain development, focus on only developing oligodendrocytes or developing neurons, not both at once. Also, it's unlikely that 27500 genes are expressed at any appreciable level. If you remove genes that are expressed at only a few copies in only a few cells, the gene selection step will go a lot faster.

**Comment by csbbcompbio** [comment]
Thanks for your invaluable suggestions. I will input the pre-filtered matrix to SLICER.


Have a great evening !!

Cheers !!
Praneet
